fos_oauth_server:
    db_driver:  orm
    client_class: WPA\APIBundle\Entity\Client
    access_token_class: WPA\APIBundle\Entity\AccessToken
    refresh_token_class: WPA\APIBundle\Entity\RefreshToken
    auth_code_class: WPA\APIBundle\Entity\AuthCode 
    service:
        user_provider: fos_user.user_provider.username
        storage:                fos_oauth_server.storage.default 
        client_manager:         fos_oauth_server.client_manager.default
        access_token_manager:   fos_oauth_server.access_token_manager.default
        refresh_token_manager:  fos_oauth_server.refresh_token_manager.default
        auth_code_manager:      fos_oauth_server.auth_code_manager.default
    authorize:
        form:
            type:               fos_oauth_server_authorize
            handler:            fos_oauth_server.authorize.form.handler.default
            name:               fos_oauth_server_authorize_form
    service:
        options:
            supported_scopes: user